version: "3.7"

services:
  gamedaybot:
    build:
      context: .
    restart: always
    environment:
      #Bot ID from the GroupMe developers page (REQUIRED IF USING GROUPME)
      BOT_ID: "<secret>"
      LEAGUE_ID:
